/** Dial codes for login/register (digits only, no +). Order: common for South Asia first. */
export const PHONE_COUNTRY_OPTIONS: ReadonlyArray<{ code: string; label: string }> = [
  { code: "91", label: "India (+91)" },
  { code: "92", label: "Pakistan (+92)" },
  { code: "880", label: "Bangladesh (+880)" },
  { code: "94", label: "Sri Lanka (+94)" },
  { code: "977", label: "Nepal (+977)" },
  { code: "93", label: "Afghanistan (+93)" },
  { code: "971", label: "UAE (+971)" },
  { code: "966", label: "Saudi Arabia (+966)" },
  { code: "974", label: "Qatar (+974)" },
  { code: "965", label: "Kuwait (+965)" },
  { code: "968", label: "Oman (+968)" },
  { code: "973", label: "Bahrain (+973)" },
  { code: "1", label: "USA / Canada (+1)" },
  { code: "44", label: "United Kingdom (+44)" },
  { code: "61", label: "Australia (+61)" },
  { code: "49", label: "Germany (+49)" },
  { code: "33", label: "France (+33)" },
  { code: "39", label: "Italy (+39)" },
  { code: "34", label: "Spain (+34)" },
  { code: "7", label: "Russia / Kazakhstan (+7)" },
  { code: "86", label: "China (+86)" },
  { code: "81", label: "Japan (+81)" },
  { code: "82", label: "South Korea (+82)" },
  { code: "65", label: "Singapore (+65)" },
  { code: "60", label: "Malaysia (+60)" },
  { code: "62", label: "Indonesia (+62)" },
  { code: "66", label: "Thailand (+66)" },
  { code: "84", label: "Vietnam (+84)" },
  { code: "63", label: "Philippines (+63)" },
  { code: "27", label: "South Africa (+27)" },
  { code: "234", label: "Nigeria (+234)" },
  { code: "254", label: "Kenya (+254)" },
  { code: "20", label: "Egypt (+20)" },
  { code: "90", label: "Turkey (+90)" },
  { code: "98", label: "Iran (+98)" },
  { code: "964", label: "Iraq (+964)" }
];
